server:
  port: 20190

eureka:
  instance:
    hostname: 192.168.122.102
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

